/**
 * Predefined language codes with names and native-script translations.
 * Shared by Languages page and any other component that needs this list.
 */
export interface LanguageOptionConfig {
  name: string;
  code: string;
  nativeName: string;
}

export const LANGUAGE_OPTIONS: LanguageOptionConfig[] = [
  { name: 'Hindi', code: 'hi', nativeName: 'हिंदी' },
  { name: 'Bengali', code: 'bn', nativeName: 'বাংলা' },
  { name: 'Tamil', code: 'ta', nativeName: 'தமிழ்' },
  { name: 'Telugu', code: 'te', nativeName: 'తెలుగు' },
  { name: 'Marathi', code: 'mr', nativeName: 'मराठी' },
  { name: 'Gujarati', code: 'gu', nativeName: 'ગુજરાતી' },
  { name: 'Punjabi', code: 'pa', nativeName: 'ਪੰਜਾਬੀ' },
  { name: 'Urdu', code: 'ur', nativeName: 'اردو' },
  { name: 'Malayalam', code: 'ml', nativeName: 'മലയാളം' },
  { name: 'Kannada', code: 'kn', nativeName: 'ಕನ್ನಡ' },
  { name: 'Odia', code: 'or', nativeName: 'ଓଡ଼ିଆ' },
  { name: 'Assamese', code: 'as', nativeName: 'অসমীয়া' },
  { name: 'Nepali', code: 'ne', nativeName: 'नेपाली' },
  { name: 'Sanskrit', code: 'sa', nativeName: 'संस्कृतम्' },
  { name: 'Sindhi', code: 'sd', nativeName: 'سنڌي' },
  { name: 'Konkani', code: 'kok', nativeName: 'कोंकणी' },
  { name: 'Manipuri (Meitei)', code: 'mni', nativeName: 'ꯃꯩꯇꯩꯂꯣꯟ' },
  { name: 'Bodo', code: 'brx', nativeName: 'बड़ो' },
  { name: 'Dogri', code: 'doi', nativeName: 'डोगरी' },
  { name: 'Maithili', code: 'mai', nativeName: 'मैथिली' },
  { name: 'Santali', code: 'sat', nativeName: 'ᱥᱟᱱᱛᱟᱲᱤ' },
  { name: 'Kashmiri', code: 'ks', nativeName: 'कश्मीरी / کشمیری' },
  { name: 'Tulu', code: 'tcy', nativeName: 'ತುಳು' },
  { name: 'Bhojpuri', code: 'bho', nativeName: 'भोजपुरी' },
  { name: 'Rajasthani', code: 'raj', nativeName: 'राजस्थानी' },
  { name: 'Haryanvi', code: 'bgc', nativeName: 'हरियाणवी' },
  { name: 'Chhattisgarhi', code: 'hne', nativeName: 'छत्तीसगढ़ी' },
  { name: 'Garhwali', code: 'gbm', nativeName: 'गढ़वाली' },
  { name: 'Kumaoni', code: 'kfy', nativeName: 'कुमाऊँनी' },
  { name: 'Magahi', code: 'mag', nativeName: 'मगही' },
  { name: 'Angika', code: 'anp', nativeName: 'अंगिका' },
  { name: 'Awadhi', code: 'awa', nativeName: 'अवधी' },
  { name: 'Bundeli', code: 'bns', nativeName: 'बुंदेली' },
  { name: 'Bagheli', code: 'bfy', nativeName: 'बघेली' },
  { name: 'Ladakhi', code: 'lbj', nativeName: 'ལ་དྭགས་སྐད་' },
  { name: 'Gondi', code: 'gon', nativeName: 'गोंडी' },
  { name: 'Bhili', code: 'bhb', nativeName: 'भीली' },
  { name: 'Khasi', code: 'kha', nativeName: 'खासी' },
  { name: 'Mizo (Lushai)', code: 'lus', nativeName: 'Mizo ṭawng' },
  { name: 'Ao', code: 'njo', nativeName: 'Ao' },
  { name: 'Nyishi', code: 'nyi', nativeName: 'Nyishi' },
  { name: 'Lepcha', code: 'lep', nativeName: 'ᰛᰩᰵᰛᰵ' },
  { name: 'Kokborok', code: 'trp', nativeName: 'Kokborok' },
  { name: 'Ho', code: 'hoc', nativeName: 'ᱦᱳ' },
  { name: 'Kurukh (Oraon)', code: 'kru', nativeName: 'कुड़ुख' },
  { name: 'Mundari', code: 'unr', nativeName: 'मुंडारी' },
  { name: 'Sora', code: 'srb', nativeName: 'ସୋରା' },
  { name: 'Nicobarese', code: 'ncb', nativeName: 'Nicobarese' },
  { name: 'Kodava', code: 'kfa', nativeName: 'ಕೊಡವ' },
  { name: 'Badaga', code: 'bfq', nativeName: 'ಬಡಗ' },
  { name: 'Pahari', code: 'phr', nativeName: 'पहाड़ी' },
  { name: 'Marwari', code: 'mwr', nativeName: 'मारवाड़ी' },
  { name: 'Mewari', code: 'mtr', nativeName: 'मेवाड़ी' },
  { name: 'Dhundhari', code: 'dhd', nativeName: 'ढूंढाड़ी' },
  { name: 'Khandeshi', code: 'khn', nativeName: 'खानदेशी' },
  { name: 'Surjapuri', code: 'sjp', nativeName: 'सुरजापुरी' },
  { name: 'Dimasa', code: 'dis', nativeName: 'Dimasa' },
  { name: 'Karbi', code: 'mjw', nativeName: 'Karbi' },
  { name: 'Garo', code: 'grt', nativeName: 'Garo' },
];

